[features]
seeds = false
[programs.devnet]
propulsion = "8i4YZYcxNpEZXHDYkhP2Ewv62jZVxvR193H8yb7sxqu1"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/patrickwide/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
